Models/ErrorViewModel.cs
using System;

namespace WebShop.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Osoba.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebShop.Models
{
    public class Osoba
    {
        public int OsobaId { get; set; }
        public string ImePrezime { get; set; }
        public string Telefon { get; set; }
        public string Ulica { get; set; }
        public string KucniBroj { get; set; }
        public string PostanskiBroj { get; set; }
        public string Mesto { get; set; }
        public string StaPorucujete { get; set; }
        public int Kolicina { get; set; }
        
    }
}

Models/OsobaCon.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace WebShopClient.Models
{

    [DataContract]
    public class OsobaCon
    {
        [DataMember]
        public int OsobaId { get; set; }

        [DataMember(IsRequired = false)]
        public string ImePrezime { get; set; }

        [DataMember(IsRequired = false)]
        public string Telefon { get; set; }
        [DataMember(IsRequired = false)]
        public string Ulica { get; set; }
        [DataMember(IsRequired = false)]
        public string KucniBroj { get; set; }
        [DataMember(IsRequired = false)]
        public string PostanskiBroj { get; set; }
        [DataMember(IsRequired = false)]
        public string Mesto { get; set; }
        [DataMember(IsRequired = false)]
        public string StaPorucujete { get; set; }
        [DataMember(IsRequired = false)]
        public int Kolicina { get; set; }
    }
    
}

Models/Porucbenica.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebShopClient.Models
{
    [Table("Porucbenica")]
    public partial class Porucbenica
    {
        public int OsobaId { get; set; }
        public string ImePrezime { get; set; }
        public string Telefon { get; set; }
        public string Ulica { get; set; }
        public string KucniBroj { get; set; }
        [StringLength(50)]
        public string PostanskiBroj { get; set; }
        [StringLength(50)]
        public string Mesto { get; set; }
        [StringLength(50)]
        public string StaPorucujete { get; set; }
        public int? Kolicina { get; set; }
    }
}

Models/WebshopdbContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Newtonsoft.Json;

namespace WebShopClient.Models
{
    public partial class WebshopdbContext : DbContext
    {
        public WebshopdbContext()
        {
        }

        public WebshopdbContext(DbContextOptions<WebshopdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Porucbenica> Porucbenicas { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<Porucbenica>(entity =>
            {
                entity.HasKey(e => e.OsobaId)
                    .HasName("PK__Porucben__BD4904F59B36515A");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OsobaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ServiceReference1;
using WebShop.Models;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebShop.Controllers
{
   
    public class OsobaController : Controller 
    {
      
        [HttpGet]
        public IActionResult Index()
        {          
            return View();
        }

        public IActionResult Ubaci()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ubaci(Porucbenica os)
        {
            WebShopServiceClient client = new WebShopServiceClient();
             Porucbenica os1 = new Porucbenica();
            Global.proizvod = os.StaPorucujete;
            Global.kolicina = os.Kolicina;
            os1.ImePrezime = os.ImePrezime;
            os1.Telefon = os.Telefon;
            os1.Ulica = os.Ulica;
            os1.KucniBroj = os.KucniBroj;
            os1.PostanskiBroj = os.PostanskiBroj;
            os1.Mesto = os.Mesto;
            os1.StaPorucujete = os.StaPorucujete;
            os1.Kolicina = os.Kolicina;
            client.OpenAsync();
            
            client.PreuzmiOsobeAsync(os1);
                
            client.CloseAsync();
            
            return RedirectToAction("Index");

        }
    }
}

Controllers/PorudzbenicaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebShopClient.Models;

namespace WebShopClient.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class PorudzbenicaController : ControllerBase
    {
        private readonly WebshopdbContext db;

        public PorudzbenicaController(WebshopdbContext _db)
        {
            db = _db;
        }
        [HttpGet]
        public IEnumerable<Porucbenica> VratiPorudzbenicu()
        {
            return db.Porucbenicas;
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@*<div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>*@

Views/Osoba/Index.cshtml
@model IEnumerable<WebShop.Models.Osoba>

@{
    ViewData["Title"] = "Porudzbina";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Primljena porudzbina</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <link href="~/css/site.css" rel="stylesheet" />
    <style>
        #spanh1 {
            color: red;           
        } 
        body{ background-color:deepskyblue;}
    </style>
</head>
<body>
    <div>
        <center>
            <h1>Vasa Porudzbina je</h1>
        </center>
    </div>
    <div>
        <center>
            <h1 id="h"><span id="spanh1">PRIMLJENA</span>!</h1>
        </center>
    </div>
    <div>
        <center>
            <h3>Vasa porudzbina</h3>
        </center>
    </div>
    <div class="container">
        <div class="row" style="display:flex;flex-direction:column; justify-self:center;align-items:center; position:center;text-align:center; ">
            <center>
                <div>
                    <div id="table1">
                         
                        <table class="table table-bordered" style=" background-color:greenyellow;">
                            <thead>
                                <tr>
                                    <th>Naziv artikla:</th>
                                    <th>Kolicina:</th>
                                    <th>Cena:</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    
                                    <td>@Global.proizvod</td>
                                    <td>@Global.kolicina</td>
                                    <td>0.00 <br>RSD</td>
                                </tr>
                                <tr>
                                    <td style="text-align: left " colspan="2"><b> Postarina:</b></td>
                                    <td>0.00 <br> RSD </td>
                                </tr>
                                <tr>
                                    <td style="text-align: left " colspan="2"> <b>Ukupno:</b></td>
                                    <td class="table-primary">0.00 <br> RSD</td>
                                </tr>
                            </tbody>
                        </table>

                    </div>
                </div>
            </center>
        </div>
        <div style="text-align: center">
            <div>
                <p>

                    Hvala vam sto ste izabrali Facebook Shop ZMAJ za vas shoping. Vasa porudzbina je primljena. Placanje je prilikom preuzimanja(sigurna kupovina).

                </p>

            </div>
            <div>
                <p>

                    Dostavu vrsi kurirska sluzba ROYAL EXPRESS.

                </p>
                <p>

                    Isporuka ce biti kroz 4-7 radnih dana.

                </p>

            </div>
            <div>
                <p>

                    Ukoliko ne dobijete vasu posiljku ni nakon 7 dana, javite nam se da mozemo proveriti sta se dogobilo.

                </p>

            </div>
            <div>
                <p>

                    OBAVEZNO OSTAVITE PRAVI BROJ MOBILNOG TELEFONA, KAKO BI VAS MOGLA KONTAKTIRATI KURIRSKA SLUZBA.

                </p>

            </div>
            <a href='javascript:history.go(-2)' style="color:greenyellow ;border:solid">klikni ovde da bi se vratio na stranicu sa proizvodima</a>
        </div>

    </div>
</body>

</html>

Views/Osoba/Ubaci.cshtml
@model WebShop.Models.Osoba

@{
    ViewData["Title"] = "Porudzbina";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="~/css/site.css" rel="stylesheet" />
<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
<h1></h1>
<style>    body {background-color:deepskyblue;
    }
</style>
<h4>Unesite vase podatke</h4>
<hr />
<div class="row">
    <div class="col-4 col-auto">
        <form asp-action="Ubaci(Porudzbenica os)" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                    <label asp-for="OsobaId" class="control-label"></label>
                    <input asp-for="OsobaId" class="form-control" />
                    <span asp-validation-for="OsobaId" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="ImePrezime" class="control-label">Ime i prezime</label>
                <input asp-for="ImePrezime" class="form-control" />
                <span asp-validation-for="ImePrezime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefon" class="control-label"></label>
                <input asp-for="Telefon" class="form-control" />
                <span asp-validation-for="Telefon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ulica" class="control-label"></label>
                <input asp-for="Ulica" class="form-control" />
                <span asp-validation-for="Ulica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KucniBroj" class="control-label">Kucni broj</label>
                <input asp-for="KucniBroj" class="form-control" />
                <span asp-validation-for="KucniBroj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostanskiBroj" class="control-label">Postanski broj</label>
                <input asp-for="PostanskiBroj" class="form-control" />
                <span asp-validation-for="PostanskiBroj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mesto" class="control-label"></label>
                <input asp-for="Mesto" class="form-control" />
                <span asp-validation-for="Mesto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StaPorucujete" class="control-label">Sta porucujete</label>
                <input asp-for="StaPorucujete" class="form-control" />
                <span asp-validation-for="StaPorucujete" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kolicina" class="control-label"></label>
                <input asp-for="Kolicina" class="form-control" />
                <span asp-validation-for="Kolicina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button id="Button1" type="submit" class="btn btn-success border-dark btn-lg">
                    <span class="glyphicon glyphicon-shopping-cart"> Poruci </span>
                </button>
            </div>
        </form>
    </div>
</div>

<div>
    <a href='javascript:history.go(-1)'>Vrati se na stranicu sa proizvodima</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebShop</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Osoba" asp-action="Ubaci">WebShopNow</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Osoba" asp-action="Index">Osobe</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        
        @*<partial name="_CookieConsentPartial" />*@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="align-content:center">
        <div class="container">
             - Web Shop - 
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>